version: '3.7'

networks:
  dev:
    driver: bridge

volumes:
  mysql_db_data:
    driver: local
  maria_db_data:
    driver: local

services:
  httpd:
    container_name: ${DOCKER_DOMAIN}-httpd
    image: ${DOCKER_DOMAIN}-php:7.2.15-apache
    build:
      context: .
      dockerfile: Dockerfile_Httpd
    volumes:
      - ./:/var/www/html/
    ports:
      - ${DOCKER_HTTPD_PORT}:80
    networks:
      - dev
    depends_on:
      - db_mysql

  db_mysql:
    container_name: ${DOCKER_DOMAIN}-mysql
    image: mysql:8.0.12
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - dev
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: ${DOCKER_DOMAIN}-phpmyadmin
    image: bitnami/phpmyadmin:4.8.4
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    networks:
      - dev
    environment:
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=1
      - DATABASE_HOST=${DOCKER_DOMAIN}-${DB_CONNECTION}
      - DATABASE_PORT_NUMBER=${DOCKER_MYSQL_PORT}
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db_mysql
